
cc_binary(
    name = "bssl_aes_cbc",
    srcs = ["bssl_aes_cbc.cc"],
    deps = [
        "//lib:bssl_lib",
        "@boringssl//:ssl",
    ],
)

cc_binary(
    name = "bssl_aes_siv",
    srcs = ["bssl_aes_siv.cc"],
    deps = [
        "//lib:bssl_lib",
        "@boringssl//:ssl",
    ],
)